### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by pawamoy** [Andre601/mkdocs-pagenav-generator#2]
Hi, could you add a LICENSE file to your repository? It would help to improve https://github.com/pawamoy/best-of-mkdocs contents :slightly_smiling_face: 
If this project is unmaintained, just let me know :+1: (if it's still maintained, could you also publish it to PyPI :smile:?)

**Comment by Andre601** [comment]
> Hi, could you add a LICENSE file to your repository? It would help to improve https://github.com/pawamoy/best-of-mkdocs contents 🙂 If this project is unmaintained, just let me know 👍 (if it's still maintained, could you also publish it to PyPI 😄?)

Please read the README next time (More precisely, the [Notes](https://github.com/Andre601/mkdocs-pagenav-generator#notes) section) to know the current situation about this plugin.

Here is a tl;dr: I neither own copyright nor maintain this code here. It was made as a sort-of quick response for the awesome pages plugin thing...
Again: Read the README.

**Comment by pawamoy** [comment]
I see, sorry for missing it (I've been opening a certain number of issues and didn't take the time to read every README up to their ends), and thanks for your quick response :slightly_smiling_face:
